workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
    - when: never

stages:
  - deploy-staging

stage-deploy-staging:
  stage: deploy-staging
  image: alpine:latest

  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $STAGING_PORT $STAGING_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -p $STAGING_PORT $USER@$STAGING_HOST "cd /home/heizoelscom/quagnite && git pull && php artisan cache:clear"
  only:
    - master
